# base64 value for the word - movieticketbooking
secret_key="movieticketbooking"
mongodb_url = mongodb+srv://vercel-admin-user:movieticketbooking@cluster0.qtlta.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
database_name = movieticketbooking
smtp_email_address=born.bala.basf@gmail.com
smtp_email_password=yazw bznz ixif txng